RAM_START           equ $ff0000
PressedButtons      equ RAM_START+1
EditingFlags        equ RAM_START+2
ScrollPosition      equ RAM_START+6
randomSeed          equ RAM_START+10
currentScore        equ RAM_START+20
currentScoreEnd     equ currentScore+5
GraphicStack        equ RAM_START+100
GraphicStackPointer equ RAM_START+104
MainTimer           equ RAM_START+200
TimerArray          equ RAM_START+204 ;; consider always marking how large a memory block is and not just where it starts
WaitTimer           equ TimerArray
PressWait           equ $30
PlayerPosition      equ RAM_START+300 
PlayerXAccu         equ RAM_START+300
PlayerYAccu         equ RAM_START+304
PlayerX             equ PlayerXAccu
PlayerY             equ PlayerYAccu 
CursorPosition      equ RAM_START+400
CursorX             equ CursorPosition 
CursorY             equ CursorPosition+4
CurrentTileNo       equ CursorPosition+8
CurrentTileSize     equ CursorPosition+10
VblankStatus        equ RAM_START+500
soundIndex          equ RAM_START+506
soundTimer          equ RAM_START+510
Tilemap             equ RAM_START+$1000
TilemapEnd          equ Tilemap+64*28*2

