	;include "C:\Code\Oldschool\Megadrive\MegaOs\graphics.asm"


	dc.l   $00FFE000      
	dc.l   EntryPoint     
	dc.l   Exception     
	dc.l   AddressError    
	dc.l   IllegalInstruction   
	dc.l   Exception  
	dc.l   Exception 
	dc.l   Exception
	dc.l   Exception    
	dc.l   Exception   
	dc.l   Exception   
	dc.l   Exception  
	dc.l   Exception 
	dc.l   Exception    
	dc.l   Exception   
	dc.l   Exception      
	dc.l   Exception     
	dc.l   Exception    
	dc.l   Exception   
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   HBlankInterrupt 
	dc.l   Exception       
	dc.l   VBlankInterrupt 
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception      
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception       
	dc.l   Exception      
